/*
 * Menu.java
 * Creada el 2 de diciembre del 2021 21:11 PM
 */
package interfazFinanzas;

import java.applet.AudioClip;
import control.Control;
import excepciones.FinanzaException;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 * Menu principal de la aplicacion.
 *
 * @author Pacheco, Orozco y Cervantes
 */
public class Menu extends javax.swing.JFrame {
    Click so = new Click("/recursos/click1.wav");

    Control control = new Control();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setTitle("Menu Financiero");
        setVisible(true);
        setSize(727, 580);
        centraVentana();
        estatus();
        barras();

    }

    /**
     * Metodo que genera una barras de graficos aleatorias donde estas van
     * deacuerdo con los ingresos y egresos.
     */
    public void barras() {

        double eb = control.egresosD();
        double ib = control.ingresosD();
        if (eb == 0 && ib == 0) {
            ingresosBarras.setSize(0, 30);
            egresosBarras.setSize(0, 30);
        } else if (ib != 0 && eb == 0) {
            int mat = (int) (Math.random() * 10);
            ingresosBarras.setSize((mat * 15), 30);
            egresosBarras.setSize(0, 30);
        } else if (ib == 0 && eb != 0) {
            int mat = (int) (Math.random() * 10);
            egresosBarras.setSize((mat * 15), 30);
            ingresosBarras.setSize(0, 30);
        } else {
            int mat2 = 0;
            if (ib < eb) {
                while (true) {
                    mat2 = (int) (Math.random() * 10);
                    if (mat2 < 10) {
                        break;
                    }
                }
                egresosBarras.setSize((15 * 10), 30);
                ingresosBarras.setSize(15 * mat2, 30);
            } else {
                while (true) {
                    mat2 = (int) (Math.random() * 10);
                    if (mat2 < 10) {
                        break;
                    }
                }
                ingresosBarras.setSize((15 * 10), 30);
                egresosBarras.setSize(15 * mat2, 30);
            }
            if (eb == ib) {
                ingresosBarras.setSize(0, 30);
                egresosBarras.setSize(0, 30);
            }
        }
    }

    /**
     * Este método centra la ventana de la aplicación sobre la pantalla
     */
    private void centraVentana() {
        //Obtiene el tamaño de la pantalla 
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Obtiene el tamaño de la ventana de la aplicación 
        Dimension frameSize = getSize();

        // Se asegura que el tamaño de la ventana de la aplicación 
        // no exceda el tamaño de la pantalla 
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }

        // Centra la ventana de la aplicación sobre la pantalla 
        setLocation((screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        FinanzasNet = new javax.swing.JButton();
        Interes = new javax.swing.JButton();
        Egresos = new javax.swing.JButton();
        Ingresos = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        Estado = new javax.swing.JLabel();
        Estado2 = new javax.swing.JLabel();
        Estado3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Estado5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ingresosBarras = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        egresosBarras = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        ingresosTotal = new javax.swing.JLabel();
        egresosTotal1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setFocusable(false);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 153, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        FinanzasNet.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        FinanzasNet.setText("FINANZAS NETAS");
        FinanzasNet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinanzasNetActionPerformed(evt);
            }
        });
        jPanel2.add(FinanzasNet);
        FinanzasNet.setBounds(10, 220, 210, 40);

        Interes.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        Interes.setText("INTERÉS COMPUESTO");
        Interes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InteresActionPerformed(evt);
            }
        });
        jPanel2.add(Interes);
        Interes.setBounds(10, 150, 210, 40);

        Egresos.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        Egresos.setText("EGRESOS");
        Egresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EgresosActionPerformed(evt);
            }
        });
        jPanel2.add(Egresos);
        Egresos.setBounds(10, 90, 210, 40);

        Ingresos.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        Ingresos.setText("INGRESOS");
        Ingresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresosMouseClicked(evt);
            }
        });
        Ingresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresosActionPerformed(evt);
            }
        });
        jPanel2.add(Ingresos);
        Ingresos.setBounds(10, 30, 210, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(40, 90, 230, 280);

        Titulo.setBackground(new java.awt.Color(204, 204, 0));
        Titulo.setFont(new java.awt.Font("STCaiyun", 3, 36)); // NOI18N
        Titulo.setText("NET  FINANCES");
        jPanel1.add(Titulo);
        Titulo.setBounds(270, 30, 290, 40);

        jPanel3.setBackground(new java.awt.Color(204, 204, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);
        jPanel1.add(jPanel3);
        jPanel3.setBounds(260, 20, 300, 60);

        jPanel5.setLayout(null);

        Estado.setFont(new java.awt.Font("Berlin Sans FB Demi", 3, 18)); // NOI18N
        Estado.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel5.add(Estado);
        Estado.setBounds(210, 10, 230, 30);

        Estado2.setFont(new java.awt.Font("Berlin Sans FB Demi", 3, 18)); // NOI18N
        Estado2.setText("ESTADO FINANCIERO: ");
        jPanel5.add(Estado2);
        Estado2.setBounds(10, 10, 190, 30);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(40, 490, 450, 50);

        Estado3.setFont(new java.awt.Font("Berlin Sans FB Demi", 3, 18)); // NOI18N
        Estado3.setText("Egreso");
        jPanel1.add(Estado3);
        Estado3.setBounds(40, 400, 60, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("|");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 370, 30, 70);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("|");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 420, 30, 50);

        Estado5.setFont(new java.awt.Font("Berlin Sans FB Demi", 3, 18)); // NOI18N
        Estado5.setText("Ingreso");
        jPanel1.add(Estado5);
        Estado5.setBounds(40, 440, 60, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Logo.PNG"))); // NOI18N
        jLabel4.setToolTipText("");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 100, 400, 260);

        ingresosBarras.setBackground(new java.awt.Color(255, 0, 0));
        ingresosBarras.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(255, 0, 0));
        jPanel6.setLayout(null);
        ingresosBarras.add(jPanel6);
        jPanel6.setBounds(140, 390, 150, 30);

        jPanel7.setBackground(new java.awt.Color(255, 0, 0));
        jPanel7.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(255, 0, 0));
        jPanel8.setLayout(null);
        jPanel7.add(jPanel8);
        jPanel8.setBounds(140, 390, 150, 30);

        ingresosBarras.add(jPanel7);
        jPanel7.setBounds(150, 390, 150, 30);

        jPanel1.add(ingresosBarras);
        ingresosBarras.setBounds(280, 440, 210, 30);

        egresosBarras.setBackground(new java.awt.Color(255, 0, 0));
        egresosBarras.setLayout(null);

        jPanel10.setBackground(new java.awt.Color(255, 0, 0));
        jPanel10.setLayout(null);
        egresosBarras.add(jPanel10);
        jPanel10.setBounds(140, 390, 150, 30);

        jPanel11.setBackground(new java.awt.Color(255, 0, 0));
        jPanel11.setLayout(null);

        jPanel12.setBackground(new java.awt.Color(255, 0, 0));
        jPanel12.setLayout(null);
        jPanel11.add(jPanel12);
        jPanel12.setBounds(140, 390, 150, 30);

        egresosBarras.add(jPanel11);
        jPanel11.setBounds(150, 390, 150, 30);

        jPanel1.add(egresosBarras);
        egresosBarras.setBounds(280, 390, 210, 30);

        ingresosTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(ingresosTotal);
        ingresosTotal.setBounds(130, 440, 140, 30);

        egresosTotal1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(egresosTotal1);
        egresosTotal1.setBounds(130, 390, 140, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 720, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents
  /**
     * Evento del boton ingresos que permite agregar un ingreso.
     *
     * @param evt Evento
     */
    private void IngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresosActionPerformed
        so.run();
        Thread hilo = Thread.currentThread();
        try {
            hilo.sleep(100);
        } catch (InterruptedException e) {
        }
        try {
            control.agregarIngreso(this);
            estatus();
            barras();
        } catch (FinanzaException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_IngresosActionPerformed
    /**
     * Evento del boton egresos que permite agregar un egreso.
     *
     * @param evt Evento
     */
    private void EgresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EgresosActionPerformed
        so.run();
        Thread hilo = Thread.currentThread();
        try {
            hilo.sleep(100);
        } catch (InterruptedException e) {
        }
        try {
            control.agregarEgreso(this);
            estatus();
            barras();
        } catch (FinanzaException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_EgresosActionPerformed
    /**
     * Metodo que permite obtener los estatus actuales de egresos, ingresos y
     * sus respectivas graficas de barras.
     */
    public void estatus() {
        Estado.setText(String.valueOf(control.estadoFinanciero()));
        egresosTotal1.setText(String.valueOf(control.egresosD()));
        ingresosTotal.setText(String.valueOf(control.ingresosD()));
    }

    /**
     * Evento dek boton de finanzas netas, que manda a llamar al cuadro de
     * dialogo de finanzas, con el fin de realizar otras operaciones.
     *
     * @param evt Evento.
     */
    private void FinanzasNetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinanzasNetActionPerformed
        so.run();
        Thread hilo = Thread.currentThread();
        try {
            hilo.sleep(100);
        } catch (InterruptedException e) {
        }
        DlgFinanzas dlg = new DlgFinanzas(null, "Finanzas Netas", true);
        estatus();
        barras();
    }//GEN-LAST:event_FinanzasNetActionPerformed
    /**
     * Evento del boton interes de que manda a llamar al cuadro de dialo de
     * interes con el fin de usar la calculadora de interes compuesto.
     *
     * @param evt Evento
     */
    private void InteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InteresActionPerformed
         so.run();
        Thread hilo = Thread.currentThread();
        try {
            hilo.sleep(100);
        } catch (InterruptedException e) {
        }
        DlgInteres d = new DlgInteres(null, "Calculadora de interes Compuesto", true);
    }//GEN-LAST:event_InteresActionPerformed

    private void IngresosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresosMouseClicked
        // TODO add your handling code here:
//        AudioClip sonido;
//        sonido=java.applet.Applet.newAudioClip(getClass().getResource("/recursos/click1.wav"));
//        sonido.play();
    }//GEN-LAST:event_IngresosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Egresos;
    private javax.swing.JLabel Estado;
    private javax.swing.JLabel Estado2;
    private javax.swing.JLabel Estado3;
    private javax.swing.JLabel Estado5;
    private javax.swing.JButton FinanzasNet;
    private javax.swing.JButton Ingresos;
    private javax.swing.JButton Interes;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel egresosBarras;
    private javax.swing.JLabel egresosTotal1;
    private javax.swing.JPanel ingresosBarras;
    private javax.swing.JLabel ingresosTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
