/*
 * Lienzo.java
 */
package interfazUsuario;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;

/**
 * Esta clase hereda de JPanel e implementa un lienzo. Se puede borrar 
 * el lienzo, desplegar una imagen o dibujar sobre una imagen
 *
 * @author Manuel Domitsu
 */
public class Lienzo extends javax.swing.JPanel {

  /**
   * Crea un lienzo y lo inicializa
   */
  public Lienzo() {
    initComponents();
  }

  /**
   * Regresa la imagen a desplegar o sobre la que se dibuja
   * @return Imagen a desplegar o sobre la que se dibuja
   */
  public BufferedImage getImagen() {
    return imagen;
  }

  /**
   * Estable la imagen a desplegar o sobre la que se dibuja
   * @param imagen Imagen a desplegar o sobre la que se dibuja
   */
  public void setImagen(BufferedImage imagen) {
    this.imagen = imagen;
  }

  /**
   * Metódo que dibuja sobre el panel
   * @param g Objeto con el contexto de graficación
   */
  @Override
  public void paintComponent(Graphics g) {
    Graphics2D g2 = (Graphics2D) g;
    
    if(imagen == null) return;

    // Obtiene el tamaño de la imagen
    int altoImagen = imagen.getHeight();
    int anchoImagen = imagen.getWidth();

    // Establece el tamaño del panel al tamaño de la imagen
    setPreferredSize(new Dimension(altoImagen, anchoImagen));
    revalidate();

    // Dibuja la imagen sobre el panel
    g2.drawImage(imagen, null, 1, 1);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

  private BufferedImage imagen;
}
