/*
 * DlgCategorias.java
 * Creada el 2 de diciembre del 2021 21:11 PM
 */
package interfazFinanzas;

import java.awt.Dimension;
import java.awt.Point;
import javax.swing.JOptionPane;

/**
 * Cuadro de dialogo que pemite obtener la categoria a buscar.
 * @author Equipo 1
 */
public class DlgCategorias extends javax.swing.JDialog {

    private boolean rutina = false;
    private boolean transporte = false;
    private boolean familia = false;
    private boolean alimentacion = false;
    private boolean regalos = false;
    private boolean educacion = false;
    private boolean salud = false;
    private StringBuffer respuesta;
    private String c;
    private int operacion;

    /**
     * Creates new form DlgCategorias
     *
     * @param parent Paren
     * @param title Titulo del cuadro de dialogo
     * @param modal Modal 
     * @param mensaje Mensaje
     * @param respuesta Respuesta
     * @param operacion Operacion a realizar
     */
    public DlgCategorias(java.awt.Frame parent, String title, boolean modal, String mensaje, StringBuffer respuesta, int operacion) {
        super(parent, title, modal);
        initComponents();
        this.operacion = operacion;
        this.respuesta = respuesta;
        this.c = mensaje;
        setSize(650, 520);
        respuesta.append(ConstantesGUI.CANCELAR);
        centraCuadroDialogo(parent);
        setLocationRelativeTo(null);
        setVisible(true);
    }
  /**
   * Metodo que centra el cuadro de dialogo
   * @param parent  Parent
   */
    private void centraCuadroDialogo(java.awt.Frame parent) {
        Dimension frameSize = parent.getSize();
        Point loc = parent.getLocation();

        Dimension dlgSize = getPreferredSize();

        setLocation((frameSize.width - dlgSize.width) / 2 + loc.x, (frameSize.height - dlgSize.height) / 2 + loc.y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonCancelar = new javax.swing.JButton();
        botonRestaurar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botonAlimentacion = new javax.swing.JButton();
        botonEducacion = new javax.swing.JButton();
        botonSalud = new javax.swing.JButton();
        botonRegalos = new javax.swing.JButton();
        botonFamilia = new javax.swing.JButton();
        botonRutina = new javax.swing.JButton();
        botonTransporte = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        categoriaJ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));
        jPanel1.setLayout(null);

        botonCancelar.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(153, 0, 0));
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCancelar);
        botonCancelar.setBounds(470, 420, 120, 30);

        botonRestaurar.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        botonRestaurar.setForeground(new java.awt.Color(153, 0, 0));
        botonRestaurar.setText("Restaurar");
        botonRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestaurarActionPerformed(evt);
            }
        });
        jPanel1.add(botonRestaurar);
        botonRestaurar.setBounds(270, 420, 120, 30);

        botonAceptar.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        botonAceptar.setForeground(new java.awt.Color(153, 0, 0));
        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(botonAceptar);
        botonAceptar.setBounds(50, 420, 120, 30);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel2.setText("Categorias");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 20, 250, 50);

        jPanel2.setBackground(new java.awt.Color(153, 153, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.setLayout(null);

        botonAlimentacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Bread_icon-icons.com_68777.png"))); // NOI18N
        botonAlimentacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        botonAlimentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAlimentacionActionPerformed(evt);
            }
        });
        jPanel2.add(botonAlimentacion);
        botonAlimentacion.setBounds(250, 40, 90, 80);

        botonEducacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/3069198-cap-education-hat-school_112714.png"))); // NOI18N
        botonEducacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        botonEducacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEducacionActionPerformed(evt);
            }
        });
        jPanel2.add(botonEducacion);
        botonEducacion.setBounds(490, 20, 100, 100);

        botonSalud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1-80_icon-icons.com_65644.png"))); // NOI18N
        botonSalud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        botonSalud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSaludActionPerformed(evt);
            }
        });
        jPanel2.add(botonSalud);
        botonSalud.setBounds(490, 170, 100, 90);

        botonRegalos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/free-30-instagram-stories-icons36_122584.png"))); // NOI18N
        botonRegalos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        botonRegalos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegalosActionPerformed(evt);
            }
        });
        jPanel2.add(botonRegalos);
        botonRegalos.setBounds(360, 110, 100, 100);

        botonFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/306familymanwomangirlgirl2_100722.png"))); // NOI18N
        botonFamilia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        botonFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFamiliaActionPerformed(evt);
            }
        });
        jPanel2.add(botonFamilia);
        botonFamilia.setBounds(130, 110, 101, 90);

        botonRutina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/st_patricks_day_calendar_celebration_holiday_icon_132875.png"))); // NOI18N
        botonRutina.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        botonRutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRutinaActionPerformed(evt);
            }
        });
        jPanel2.add(botonRutina);
        botonRutina.setBounds(20, 20, 90, 90);

        botonTransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/bustransport_bus_4984.png"))); // NOI18N
        botonTransporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        botonTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTransporteActionPerformed(evt);
            }
        });
        jPanel2.add(botonTransporte);
        botonTransporte.setBounds(20, 160, 90, 80);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Categoria seleccionada;");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 250, 220, 40);

        categoriaJ.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(categoriaJ);
        categoriaJ.setBounds(300, 250, 170, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 90, 620, 310);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 640, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   /**
    * Evento del boton familiar.
    * @param evt  Evento
    */
    private void botonFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFamiliaActionPerformed
        categoriaJ.setText("Familia");
        rutina = false;
        transporte = false;
        familia = true;
        alimentacion = false;
        regalos = false;
        educacion = false;
        salud = false;
    }//GEN-LAST:event_botonFamiliaActionPerformed
  /**
    * Evento del boton Transporte
    * @param evt  Evento
    */
    private void botonTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTransporteActionPerformed
        categoriaJ.setText("Transporte");
        rutina = false;
        transporte = true;
        familia = false;
        alimentacion = false;
        regalos = false;
        educacion = false;
        salud = false;
    }//GEN-LAST:event_botonTransporteActionPerformed
  /**
    * Evento del boton Alimentacion
    * @param evt  Evento
    */
    private void botonAlimentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAlimentacionActionPerformed
        categoriaJ.setText("Alimentación");
        rutina = false;
        transporte = false;
        familia = false;
        alimentacion = true;
        regalos = false;
        educacion = false;
        salud = false;
    }//GEN-LAST:event_botonAlimentacionActionPerformed
  /**
    * Evento del boton salud.
    * @param evt  Evento
    */
    private void botonSaludActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSaludActionPerformed
        categoriaJ.setText("Salud");
        rutina = false;
        transporte = false;
        familia = false;
        alimentacion = false;
        regalos = false;
        educacion = false;
        salud = true;
    }//GEN-LAST:event_botonSaludActionPerformed
  /**
    * Evento del boton educacion.
    * @param evt  Evento
    */
    private void botonEducacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEducacionActionPerformed
        categoriaJ.setText("Educacion");
        rutina = false;
        transporte = false;
        familia = false;
        alimentacion = false;
        regalos = false;
        educacion = true;
        salud = false;
    }//GEN-LAST:event_botonEducacionActionPerformed
  /**
    * Evento del boton rutina.
    * @param evt  Evento
    */
    private void botonRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRutinaActionPerformed
        categoriaJ.setText("Rutina");
        rutina = true;
        transporte = false;
        familia = false;
        alimentacion = false;
        regalos = false;
        educacion = false;
        salud = false;

    }//GEN-LAST:event_botonRutinaActionPerformed
/**
 * Destruye el cuadro del dialogo
 * @param evt Evento
 */
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed
 /**
  * Boton aceptar que estblece el categoria a buscar.
  * @param evt Evento
  */
    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        if (operacion == ConstantesGUI.AGREGAR) {
            int i = 0, d = 0;
            boolean[] a = {rutina, transporte, familia, alimentacion, regalos, educacion, salud};
            for (int j = 0; j < a.length; j++) {
                boolean b = a[j];
                if (b == true) {
                    i = j;
                }
                if (!b) {
                    d++;
                }
            }
            if (d == a.length) {
                JOptionPane.showMessageDialog(this, "Favor de seleccionar una categoria");
            } else {
                String categoria[] = {"Rutina", "Transporte", "Familia", "Alimentacion", "Regalos", "Educacion", "Salud"};
                ConstantesGUI.AUXILIAR= categoria[i];
                respuesta.delete(0, respuesta.length());
                respuesta.append(ConstantesGUI.ACEPTAR);
                dispose();
            }
        }


    }//GEN-LAST:event_botonAceptarActionPerformed
/**
 * Metodo que restaura los valores
 * @param evt Evento
 */
    private void botonRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestaurarActionPerformed
        // TODO add your handling code here:
        categoriaJ.setText("");
        rutina = false;
        transporte = false;
        familia = false;
        alimentacion = false;
        regalos = false;
        educacion = false;
        salud = false;
    }//GEN-LAST:event_botonRestaurarActionPerformed
/**
    * Evento del boton regalos.
    * @param evt  Evento
    */
    private void botonRegalosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegalosActionPerformed
        categoriaJ.setText("Regalos");
        rutina = false;
        transporte = false;
        familia = false;
        alimentacion = false;
        regalos = true;
        educacion = false;
        salud = false;
    }//GEN-LAST:event_botonRegalosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonAlimentacion;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEducacion;
    private javax.swing.JButton botonFamilia;
    private javax.swing.JButton botonRegalos;
    private javax.swing.JButton botonRestaurar;
    private javax.swing.JButton botonRutina;
    private javax.swing.JButton botonSalud;
    private javax.swing.JButton botonTransporte;
    private javax.swing.JLabel categoriaJ;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
